/**
 * The script service: everything the plugin does to the map, shared by the commands it
 * publishes and by the Script Editor dialog. It reads the two archive members through
 * `api.document.extras`, the map's names through `api.settings` / `api.names` /
 * `api.query`, compiles through `compile.ts`, and installs a build with one
 * `document.update` — a settings-style transaction, outside the undo model, exactly as
 * the editor's own trigger dialogs write.
 */
import type { PluginApi, TriggerClaimHandle } from "./plugin-api/plugins/api";
import type { TriggerRecord } from "./vendor/triggers";
import { compileInBackground } from "./compile";
import type { CompileOptions, CompileResult } from "./compiler/compiler";
import { generateDeclarations } from "./compiler/declarations";
import { scriptNames, type ScriptNames } from "./compiler/names";
import { printScript } from "./compiler/print";
import { simulate, type SimulationEvent } from "./compiler/simulate";
import {
  buildScript, findBlock, isScriptMember, readManifest, relocateManifest, reservedStorage, scriptState, triggerAtLine, withScript,
  type BuildOptions, type Extras, type ScriptBlock, type ScriptState,
} from "./script";

export interface ScriptBuildResult {
  compiled: CompileResult;
  /** Where the block landed; null when the compile had errors and nothing was built. */
  block: ScriptBlock | null;
}

export interface ScriptSimulation {
  cycles: number;
  events: SimulationEvent[];
  /** Indices of the switches that are set at the end. */
  switches: number[];
}

export interface MapNames {
  names: ScriptNames;
  /** The generated `.d.ts`. */
  decls: string;
  /** Storage the map's hand triggers already use, for the allocator to avoid. */
  options: CompileOptions;
}

/** The two script members as the map holds them, by their stored names. */
export function snapshotExtras(api: PluginApi): Map<string, Uint8Array> {
  const out = new Map<string, Uint8Array>();
  for (const name of api.document.extras.list()) {
    if (!isScriptMember(name)) continue;
    const bytes = api.document.extras.get(name);
    if (bytes) out.set(name, bytes);
  }
  return out;
}

/** Write the difference between two snapshots back to the map (marks it modified when anything changes). */
export function commitExtras(api: PluginApi, before: Extras, after: Extras): void {
  for (const name of before.keys()) if (!after.has(name)) api.document.extras.remove(name);
  for (const [name, bytes] of after) if (before.get(name) !== bytes) api.document.extras.set(name, bytes);
}

export class ScriptService {
  readonly api: PluginApi;
  readonly claim: TriggerClaimHandle;
  private lastManifest: Uint8Array | null | undefined;

  constructor(api: PluginApi, open: (line?: number) => void) {
    this.api = api;
    this.claim = api.triggers.claim({
      label: "the trigger script",
      badge: "script",
      locate: (list) => {
        const manifest = readManifest(snapshotExtras(api));
        return manifest ? findBlock(list, manifest) : null;
      },
      describe: (index, list) => {
        const line = this.lineOf(index, list);
        return `This trigger is generated by the map's trigger script${line ? ` (line ${line})` : ""}. Edit the source instead; a Build replaces the whole block.`;
      },
      open: (index, list) => open(this.lineOf(index, list) ?? undefined),
      openLabel: "Open Script Editor",
    });
  }

  private lineOf(index: number, list: TriggerRecord[]): number | undefined {
    const manifest = readManifest(snapshotExtras(this.api));
    const block = manifest ? findBlock(list, manifest) : null;
    return block ? block.lines[index - block.start] : undefined;
  }

  /** The map's script source, its manifest, and whether the built block is still intact. Null with no map. */
  state(): ScriptState | null {
    if (!this.api.document.isOpen()) return null;
    return scriptState(this.api.triggers.list(), snapshotExtras(this.api));
  }

  /** The tables and the `.d.ts` for the open map — its forces, used locations, switch names and custom unit names. Null with no map. */
  names(): MapNames | null {
    const api = this.api;
    const info = api.document.info();
    if (!info) return null;
    const custom = new Map(api.settings.unitTypes().map((u) => [u.id, u.customName]));
    // Used locations: every slot with a box on the map (Anywhere is added by the tables when it is not listed).
    const used = [...new Set(api.query.locationsIn({ x0: 0, y0: 0, x1: info.width, y1: info.height }))].sort((a, b) => a - b);
    const switchNames = api.triggers.switchNames();
    const names = scriptNames({
      forceNames: api.settings.forces().map((f) => f.name || null),
      locations: used.map((index) => ({ index, name: api.names.location(index) })),
      switchNames,
      unitCustomName: (id) => custom.get(id) || null,
    });
    const triggers = api.triggers.list();
    const state = scriptState(triggers, snapshotExtras(api));
    return { names, decls: generateDeclarations(names), options: reservedStorage(triggers, switchNames, state.block) };
  }

  declarations(): string {
    return this.names()?.decls ?? "";
  }

  /** Compile against the open map's names; rejects with `CompileSuperseded` when a newer compile started first. */
  compile(source: string): Promise<CompileResult> {
    const map = this.names();
    if (!map) return Promise.reject(new Error("No map is open."));
    return compileInBackground(source, map.decls, map.options);
  }

  /**
   * Compile and, when there are no errors, install the block — replacing the previous
   * one, or appending when the previous was edited by hand — and store the source with
   * the map. `takeOver` replaces the whole trigger list with the script's.
   */
  async build(source: string, options: BuildOptions = {}): Promise<ScriptBuildResult> {
    const compiled = await this.compile(source);
    if (!compiled.ok || !this.api.document.isOpen()) return { compiled, block: null };
    let block: ScriptBlock | null = null;
    this.api.document.update("Build trigger script", (tx) => {
      const before = snapshotExtras(this.api);
      const plan = buildScript(tx.triggers.list(), before, source, compiled, (text) => tx.strings.intern(text), options);
      tx.triggers.set(plan.list);
      commitExtras(this.api, before, plan.extras);
      block = plan.block;
    });
    this.claim.refresh();
    if (block) {
      const b: ScriptBlock = block;
      this.api.ui.status(b.count === 0 ? "Built: the script defines no triggers." : `Built ${b.count} trigger${b.count === 1 ? "" : "s"} → #${b.start + 1}–#${b.start + b.count}.`);
    }
    return { compiled, block };
  }

  /** Records as raw `trigger()` calls in the script language — what Import map triggers writes. */
  print(triggers: TriggerRecord[], header?: string): string {
    const names = this.names()?.names ?? scriptNames();
    return printScript(triggers, { names, string: (i) => this.api.names.string(i) }, header);
  }

  /** The trigger-cycle interpreter over records: Deaths, Switch, Always and Never modelled, other conditions false, other actions logged. */
  simulate(triggers: TriggerRecord[], cycles: number, options: { player?: number } = {}): ScriptSimulation {
    const sim = simulate(triggers, cycles, { player: options.player, strings: (i) => this.api.names.string(i) });
    const switches: number[] = [];
    sim.switches.forEach((v, i) => { if (v) switches.push(i); });
    return { cycles: sim.cycle, events: sim.events, switches };
  }

  /** The index of the trigger a 1-based source line generated, per the build manifest; null when none did or the block is stale. */
  triggerAtLine(line: number): number | null {
    const state = this.state();
    return state?.block && !state.stale ? triggerAtLine(state.block, line) : null;
  }

  /** The source as typed, straight into the archive (the map is modified; only Build changes triggers). */
  writeSource(text: string): void {
    if (!this.api.document.isOpen()) return;
    const before = snapshotExtras(this.api);
    commitExtras(this.api, before, withScript(before, text));
  }

  /** The hand-made triggers around the block, in list order: what Import map triggers rewrites as script. */
  handTriggers(): { before: TriggerRecord[]; after: TriggerRecord[] } {
    const list = this.api.triggers.list();
    const block = this.state()?.block ?? null;
    return block ? { before: list.slice(0, block.start), after: list.slice(block.start + block.count) } : { before: list, after: [] };
  }

  /** After the trigger list changed under the block: point the manifest at where it went. */
  relocate(): void {
    if (!this.api.document.isOpen()) return;
    const before = snapshotExtras(this.api);
    const moved = relocateManifest(this.api.triggers.list(), before);
    if (moved) commitExtras(this.api, before, moved);
  }

  /** The manifest member changed (a build, a relocation, another map): the editors should ask `locate` again. */
  manifestChanged(): boolean {
    const now = readManifestBytes(this.api);
    const changed = now !== this.lastManifest;
    this.lastManifest = now;
    return changed;
  }
}

function readManifestBytes(api: PluginApi): Uint8Array | null {
  for (const [name, bytes] of snapshotExtras(api)) if (name.toLowerCase().endsWith(".json")) return bytes;
  return null;
}
