/**
 * `python/trigscript.py` — the euddraft plugin that lowers the IR with eudplib — as a
 * TypeScript string, so the plugin can hand it to the eudplib library plugin at build
 * time without a loader. Run after editing the Python: `npm run embed`.
 * `tests/python.test.ts` fails when the two drift.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
const root = join(import.meta.dirname, "..");
const py = readFileSync(join(root, "python/trigscript.py"), "utf8");
writeFileSync(join(root, "compiler/generated/trigscriptPy.ts"), `// Generated by scripts/embed-python.mts from python/trigscript.py — do not edit.\nexport const TRIGSCRIPT_PY: string = ${JSON.stringify(py)};\n`);
console.log(`compiler/generated/trigscriptPy.ts: ${py.length} chars`);
